mushorg/conpot

- conpot/protocols/http/command_responder.py
- conpot/protocols/kamstrup/management_protocol/kamstrup_management_server.py
- conpot/protocols/kamstrup/meter_protocol/kamstrup_server.py
- conpot/protocols/modbus/modbus_server.py
- conpot/protocols/s7comm/s7_server.py
- conpot/tests/test_modbus_server.py
cherry-picked from shodan-labs/conpot
bfd26f08f4e116b048fdbcf55cc1757958aa1594
> Connection logging (open/closed)

- docs/source/installation/ubuntu.rst
Added multiverse to source, and added two required packages: python-pip and python-mysqldb
> Minor updates to Ubuntu Documentation

- .coveragerc
- .travis.yml
We should be able to see the coverage here: https://coveralls.io/r/glastopf/conpot
> Integrating conpot with coveralls

- docs/source/components/protocols/dnp3.rst
> Dnp3 proxy

- bin/conpot_cloner
> Fix snmpwalk in conpot_cloner

- conpot/protocols/kamstrup/meter_protocol/command_responder.py
- conpot/protocols/kamstrup/meter_protocol/decoder_382.py
- conpot/protocols/kamstrup/meter_protocol/kamstrup_server.py
- conpot/protocols/kamstrup/meter_protocol/messages.py
- conpot/protocols/kamstrup/meter_protocol/register.py
- conpot/protocols/kamstrup/meter_protocol/request_parser.py
@johnnykv can you do a sanity check?
> some minor cleanup

- bin/conpot
so there is only one process then
> Do not fork process when we don't want to change MAC address

- conpot/protocols/ipmi/ipmi_server.py
@glaslos please check if this any side effects that I did not notice
> Ipmi ephemeral ports

- conpot/conpot.cfg
- conpot/core/loggers/json_log.py
- conpot/core/loggers/log_worker.py
- conpot/tests/test_logger_json.py
I cherry-picked some commits from @danilo-massa #283, tweaked some stuff and added a simple unit test.
> JSON logging

- conpot/protocols/snmp/conpot_cmdrsp.py
Currently the SNMP support in Conpot just logs the request/response to the python logger but none of the information is logged such that the JSON, mysql, etc log workers see it.  This makes the SNMP support more useful in situations where the JSON output is desirable.
Sample data from output:
```
{"src_ip": "127.0.0.1", "src_port": 50375, "event_type": "SNMPv1 GetNext", "data_type": "snmp", "sensorid": "default", "timestamp": "2016-12-02T18:33:27.091827", "dst_ip": "a.b.c.d", "request": {"oid": "1.3.6.1.2.1.4.21.1.1", "val": ""}, "id": "af998209-382c-4092-906c-1c25abb46db6", "response": {"oid": "1.3.6.1.2.1.11.1.0", "val": "18"}}
```
> Update Conpot to log events for SNMP request/response

- conpot/core/loggers/mysql_log.py
I described the problems in #302
> Mysql logging

- README.rst
Add documentation for docker install using this commit.
Fix #251
> Easy Docker Container Installation Instructions

- docs/source/development/guidelines.rst
- docs/source/installation/centos.rst
Hi there,
I just adjusted the URL of the upstream repo in the documentation.
Cheers,
tpltnt
> adjusted repo URLs

- README.md
I've converted the readme to markdown since docker hub is not visualizing correctly.
I still need to test it, since docker is not working in this branch.
> From .rst readme to .md, this way docker hub will visualize correctly

- conpot/conpot.cfg
The original ones did not work or request timed out.
> change public ip providers

- README.md
Sorry, i missed a step in the readme.md in my last PR. This fixes it. Nothing important.
> Missed a step in readme.md for docker-compose instruction

- .coveragerc
- .gitignore
- conpot/core/__init__.py
- conpot/core/auth.py
- conpot/core/file_io.py
- conpot/core/virtual_fs.py
- conpot/protocols/ftp/base_handler.py
- conpot/protocols/ftp/ftp.xsd
- conpot/protocols/ftp/ftp_handler.py
- conpot/protocols/ftp/ftp_server.py
- conpot/protocols/ftp/ftp_utils.py
- conpot/protocols/ipmi/ipmi_server.py
- conpot/templates/default/ftp/ftp.xml
- conpot/tests/test_ipmi_server.py
> FTP Updates

- conpot/protocols/tftp/tftp_handler.py
> fix tftp test

- conpot/emulators/misc/random.py
In the `default/templates` section there are many uses of an auto-incrementing epoch like timer used for `SysUptime`. We ended up wanting to simulate some things randomly changing over time and figured we could contribute this code back in the hopes that it would be useful.
In any of your `template.xml` files you use `value type="function"` and point to my new functions in this PR to use my new function instead of the random static value that is generated on initial load:
```xml
<key name="memoryModbusSlave1BlockB">
<value type="function">conpot.emulators.misc.random.Random8BitRegisters</value>
</key>
<key name="memoryModbusSlave2BlockC">
<value type="function">conpot.emulators.misc.random.Random16BitRegister</value>
</key>
```
> Adds random generated functions for value functions.

- conpot/protocols/ftp/ftp_base_handler.py
Fixes  #422.
I also changed `last_active` to avoid an exception in `get_metrics` if it was never set otherwise.
> Fixed exception loop in the FTP handler

- docker/Dockerfile
Reverts mushorg/conpot#429
@sladyn98 I am reverting this PR because of breaking docker. Please feel free to send in another PR when build is fixed :slightly_smiling_face: :
> Revert "docker/dockerfile:Updated dockerfile"

- conpot/protocols/s7comm/s7.py
- conpot/protocols/s7comm/s7_server.py
- conpot/tests/helpers/s7comm_client.py
- conpot/tests/test_s7_server.py
Added the support for plc stop signal in conpot.protocols.s7comm.s7 and conpot.protocols.s7comm.s7_server to support plc stop signal (0x29).
> Added support for plc-stop signal.

- conpot/protocols/IEC104/IEC104.py
- conpot/protocols/IEC104/frames.py
Log incoming and outgoing IEC104 iframes in a more meaningful way.
> Log IEC104 iframes in a more friendly format

- requirements.txt
> fix ipmi tests

- conpot/core/attack_session.py
- conpot/core/session_manager.py
- conpot/tests/test_attack_session.py
Adds a couple of tests for `AttackSession`. Also simplifies the code a little bit.
> Test AttackSession

- conpot/protocols/enip/enip_server.py
> enip service exception issue #440 resolved

- conpot/core/databus.py
> Let get_value() of databus only evaluate the value once

- conpot/protocols/bacnet/bacnet_app.py
- conpot/protocols/enip/enip_server.py
- conpot/protocols/snmp/command_responder.py
This fixes the tests for bacnet, enpi and snmp.
For fixing the failures in bacnet-tests I had to revert [some undocumented changes](https://github.com/mushorg/conpot/commit/8c267402a95ee75de87727f9550dd0a94034e86d#diff-77e96d0150dcd0a6793da058b630fe638f765ff78e014b3c7d90a155611d70d7) (bacnet_app.py, Lines 68-69) made in https://github.com/mushorg/conpot/commit/8c267402a95ee75de87727f9550dd0a94034e86d . Hope it's ok :grimacing:
> Fix CI-Pipeline

- conpot/protocols/IEC104/IEC104_server.py
- conpot/tests/test_iec104_server.py
> Fix error handling if socket.error occurs

- bin/kamstrup_prober.py
Refactored for readability and added new def layout to reduce complexity
fixes issue #500
> Refactor bin/kamstrup_prober

- conpot/core/databus.py
- conpot/core/filesystem.py
- conpot/emulators/proxy.py
- conpot/protocols/ftp/ftp_base_handler.py
- conpot/protocols/kamstrup/management_protocol/commands.py
- conpot/protocols/kamstrup/meter_protocol/decoder_382.py
- conpot/protocols/kamstrup/meter_protocol/messages.py
- conpot/protocols/kamstrup/meter_protocol/request_parser.py
- conpot/protocols/snmp/conpot_cmdrsp.py
- conpot/tests/test_tftp.py
- conpot/tests/test_vfs.py
HI,
this PR fixes several deprecation and syntax warnings (syntax warnings appear from Python 3.8 onwards).
> Fix (most) Deprecation and Syntax Warnings
