bin/conpot
conpot/core/attack_session.py
conpot/core/databus.py
conpot/core/loggers/log_worker.py
conpot/core/loggers/mysql_log.py
conpot/core/loggers/taxii_log.py
conpot/emulators/proxy.py
conpot/protocols/http/command_responder.py
conpot/protocols/http/web_server.py
conpot/protocols/kamstrup/management_protocol/kamstrup_management_server.py
conpot/protocols/kamstrup/meter_protocol/command_responder.py
conpot/protocols/kamstrup/meter_protocol/decoder_382.py
conpot/protocols/kamstrup/meter_protocol/kamstrup_server.py
conpot/protocols/kamstrup/meter_protocol/messages.py
conpot/protocols/modbus/modbus_server.py
conpot/protocols/modbus/slave.py
conpot/protocols/snmp/build_pysnmp_mib_wrapper.py
conpot/protocols/snmp/command_responder.py
conpot/protocols/snmp/conpot_cmdrsp.py
conpot/protocols/snmp/snmp_server.py
conpot/utils/ext_ip.py

Removing Interpollation from logging scripts to reduce overhead. 
Blacklisting s7_server.py in automated script as we have to fix some bugs there.
Remaining..
conpot/protocols/s7comm/s7_server.py:58
conpot/protocols/s7comm/s7_server.py:67
conpot/protocols/s7comm/s7_server.py:111
conpot/protocols/s7comm/s7_server.py:172
conpot/protocols/s7comm/s7_server.py:177
conpot/protocols/s7comm/s7_server.py:182

Interpolation removed #211

---

conpot/protocols/modbus/modbus.xsd
conpot/protocols/modbus/modbus_server.py
conpot/protocols/modbus/slave_db.py
conpot/templates/default/modbus/modbus.xml
conpot/templates/default/template.xml

Possible solution to issue #101 
Modified slave addressing according to the preset value of mode in the modbus.xml file. The mode values are either "serial" or "tcp". Added two slaves with UIDs 0 and 255 for Modbus/TCP to the template. Added turnaround delay for Master in case of broadcasting a request over MB serial line.

Improved modbus UID handling

---

conpot/protocols/snmp/command_responder.py

to avoid:
to avoid:
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.1-py2.7-linux-i686.egg/gevent/greenlet.py", line 327, in run
result = self._run(*self.args, **self.kwargs)
File "/usr/local/lib/python2.7/dist-packages/Conpot-0.4.0-py2.7.egg/conpot/protocols/snmp/command_responder.py", line 29, in handle
self.recvCbFun(self, self.transportDomain, address, msg)
File "/usr/local/lib/python2.7/dist-packages/pysnmp/entity/engine.py", line 64, in __receiveMessageCbFun
self, transportDomain, transportAddress, wholeMsg
File "/usr/local/lib/python2.7/dist-packages/pysnmp/proto/rfc3412.py", line 416, in receiveMessage
stateReference
File "/usr/local/lib/python2.7/dist-packages/pysnmp/entity/rfc3413/cmdrsp.py", line 146, in processPdu
contextName, PDU, …

Catch Exception in snmp command responder

---

bin/conpot
conpot/conpot.cfg

In reference to issue #267, by default now conpot drops privileges to "nobody" user; the group is inferred from the gid of the "nobody" user.
User and group can be changed to whatever (e.g. conpot:conpot) by modifying the "daemon" section in `conpot.cfg`.

Allow conpot daemon to drop privileges to any user:group

---

conpot/conpot.cfg
conpot/utils/ext_ip.py

Removes telize, which shut down on 2015-11-15 (see http://www.telize.com/)

Remove telize as ip lookup service

---

conpot/protocols/guardian_ast/guardian_ast_server.py

Currently conpot just logs the session start/end but none of the useful data that is observed in between.  This logs the request and response:
```
{"src_ip": "127.0.0.1", "src_port": 56093, "event_type": "AST I20100", "data_type": "guardian_ast", "sensorid": "default", "timestamp": "2016-12-02T20:01:56.863688", "dst_ip": "a.b.c.d", "request": "\u0001I20100\n", "id": "79ee2422-5fb5-4b68-b6f5-d83e7b9a0fc8", "response": "\nI20100\n12/02/2016 20:01\n\nSTATOIL STATION\n\n\n\nIN-TANK INVENTORY\n\nTANK PRODUCT             VOLUME TC VOLUME   ULLAGE   HEIGHT    WATER     TEMP\n  1  SUPER                 4314      4344     6158    67.92     9.02    51.17\n  2  UNLEAD                7172      7357     9204    58.38     1.30    50.60\n  3  DIESEL                1998      2183     9419    44.44 …
```

Update Conpot to log events for AST request/response

---

conpot/protocols/snmp/command_responder.py

Fixes #289 and #292
Before:
```
$  snmpwalk -v2c -c public localhost 
Error in packet.
Reason: authorizationError (access denied to that object)
Failed object: SNMPv2-SMI::mib-2
SNMPv2-SMI::mib-2 = No Such Object available on this agent at this OID
```
After:
```
$  snmpwalk -v2c -c public localhost 
SNMPv2-MIB::sysDescr.0 = STRING: Siemens, SIMATIC, S7-200
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.20408
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1) 0:00:00.01
SNMPv2-MIB::sysContact.0 = STRING: Siemens AG
SNMPv2-MIB::sysName.0 = STRING: CP 443-1 EX40
...
```

Fix v2c support

---

conpot/protocols/http/http.xsd
conpot/protocols/ipmi/ipmi.xsd
conpot/protocols/modbus/modbus.xsd
conpot/protocols/s7comm/s7comm.xsd
conpot/protocols/snmp/snmp.xsd

required if altering network port for example for http honeypot (for example when use instead mhnclient with multiple honeypots like https://travis-ci.org/juju4/ansible-mhnclient)

use unsignedShort for network port

---

Dockerfile
conpot/protocols/snmp/build_pysnmp_mib_wrapper.py

We let pysmi automatically download mib files from a remote repo.

remove libsmi2ldbl and snmp-mibs-downloader dependencies 

---

requirements.txt
setup.py

Remove modbus-tk repo link from `setup.py`, add modbus-tk into `requirements.txt`

install modbus-tk from pip

---

bin/conpot

Allow interpolation of environment variables from conpot.cfg. This is useful in a docker environment in case you want settings to be controlled via `docker-compose.yml`.
Interpolation is invoked in `conpot.cfg`, for example ...
```
filename = %(HOME)s
```

Interpolate Environment Variables

---

Dockerfile
conpot/tests/test_ext_ip_util.py
conpot/tests/test_logger_mysql.py
conpot/tests/test_mac_addr.py
requirements.txt

Need to trigger the build on master **_after_** merge

Patch for #378

---

conpot/core/attack_session.py

I'm a hpfeeds user. I would be a much happier conpot user if it was closer to the json output.
This PR is a step towards this - it breaks out src ip/port and dst ip/port into seperate fields. It leaves the other fields there for now as I don't want to break other hpfeeds users.
A specific example where the current schema is annoying in ES. If i feed the conpot event stream via hpfeeds as is it will choke ES - it does not like mixed type tuples (these fields are str/int).

Break out port and ip in logger output

---

conpot/protocols/s7comm/s7.py
conpot/tests/helpers/s7comm_client.py

This pull request fixes the `param_length` calculation for the s7comm protocol introduced in the python3 migration
Python3 clearly separates text (`str` type  - unicode code points) from byte strings (class `bytes`). The `struct` module which conpot uses returns byte strings by default in py3. Unlike py2, `str` and `bytes` objects cannot be used interchangeably. The `parameters` variable in s7.py, according to the comment can either be a string or an integer. To simplify the code, conpot by default converts the value to a string before computing the length. In python3, by doing this (and if the variable is a byte string), we are appending `b'` to the original value resulting in an incorrect length calculation as exemplified below:
```
Python 3.7.0 (default, Aug 22 2018, 15:22:33)
[Clang …
```

Fix s7 parameter length calculation

---

README.md
docker/docker-compose.yml

The BACnet and IPMI ports are listed as TCP, but these services are actually UDP.

Fixed wrong Docker ports

---

bin/conpot

logger.error has now been changed to logger.exception
Fixes https://github.com/mushorg/conpot/issues/357

Changing exception

---

docker/Dockerfile

With the recent update to pip 19.01 there was a build slight issue with the docker commands, refer here:
https://github.com/pypa/pip/issues/6197, which has been fixed.

docker/dockerfile:Updated dockerfile

---

conpot/protocols/IEC104/frames.py

IEC104 is a little endian protocol, so the IOA field should be LE aswell.

fixed endianess of IOA

---

conpot/protocols/IEC104/frames.py

All floats within IEC-104 packets should be little endian.
IEEEFloatField -> FloatField

Fix endianess for floats

---

conpot/templates/IEC104/snmp/snmp.xml

Using port **161** requires root privileges.
Since Conpot drops root privileges on launch, Conpot **crashes** on start-up when trying to use port 161.
Changing the port from **161** to **16100**, as it is used in the default profile fixes the issue.

Change SNMP Port to 16100

---

bin/conpot
conpot/core/virtual_fs.py

logger.exception() should only be used inside of exception-handlers 
> This method should only be called from an exception handler.
[Python Docs](https://docs.python.org/3/library/logging.html#logging.Logger.exception)

Change log level from exception to error outside of exception handlers

---

requirements.txt

Apparently the recently release version 0.13.3 of freezegun makes our test suite fail. (`conpot.tests.test_vfs.TestSubFileSystem.test_set_time` in particular.)
The PR only skips that particular version, in the hopes that future releases will have fixed the issue.

Avoid broken dependency freezegun 0.13.3

---

conpot/core/protocol_wrapper.py
conpot/protocols/enip/enip_server.py
conpot/tests/test_enip_server.py
conpot/tests/test_protocol_wrapper.py

This PR fixes multiple issues that lead to the ENIP tests crashing without much notice. The root cause was a major bug in the `conpot_protocol` decorator. It also adds a few tests to catch regressions.
Another related issue is that Conpot (in both production code and test code) generally does not properly shut down greenlets. A general fix for that proved to be too big for this PR.
1. The ENIP test `setUp()` method was crashing, but the exceptions weren't propagated from the greenlets, thus going unnoticed. There's even a comment that acknowledges that there's something wrong:
```py
```
The first commit exposes the crashes but does not fix anything just yet.
1. The second commit fixes `conpot_protocol` allowing only a single instance reference per class:
```py …
```

Fix ENIP test crashes and conpot_protocol snafu 

---

conpot/tests/test_docs.py

`test_make_docs` would invoke `make` with the relative paths from whichever was the current working directory as the tests were being run. This PR explicitly sets `cwd`. It really just adds one line and an `import`. The rest are whitespace changes and import sorting.
This way you can invoke this test individually, e.g. from an IDE, without manually setting the working directory.

Fix test_docs being sensitive to current working directory

---

docker/Dockerfile
docs/source/installation/quick_install.rst

Updated the Dockerfile to execute the conpot binary when starting the container. Also changed documentation with easier command to run the container for testing and experimenting as part of the "quick start". The documentation does not match with the Dockerfile, because the conpot binary is not found in the $PATH because it's not exported for the conpot user.

Updated Dockerfile and documentation

---

bin/conpot
conpot/core/__init__.py
conpot/core/session_manager.py

This moves the `Databus` object out of the `SessionManager`. This allows future tests to instantiate `SessionManager`s without bothering with the databus.

Decouple Databus from SessionManager

---

requirements.txt

Pysnmp-mibs is needed to fix a deps issue after #495 with IEC104 crashing after not finding uncompiled MIBs.

Resolve deps

---

conpot/protocols/modbus/modbus_server.py

'while True' may cause infinite loop,leading to increased cpu usage，and eventually the conpot honeypot stops working.

update modbus recv

---

conpot/tests/test_ftp.py

Fixes two bugs in the FTP tests:
1. `test_appe` was leaving behind temporary files in `conpot/tests/data/data_temp_fs/ftp`
1. `test_help` contained an assert that AFAICT was always true (the one marked "test command specific help")
Since I was already looking at the file I also refactored some test initialization code.
Caveat: I saw some occasional failures in the FTP tests which looked like race conditions to me, where one test would sometimes find a file another test had created. I don't think my particular changes are to blame but I can't be sure.

Fix FTP test leaving behind temporary files

---

conpot/protocols/IEC104/frames.py

All values for the IEC104 protocol should be little endian.

Fix Wrong Endianness for IEC104 Types 100-103

---

conpot/tests/test_ipmi_server.py

This /should/ fix the test failures in #529, in three-ish steps:
1. Expose the error message by redirecting `stderr` to `stdout`, i. e. failed `assert`s now show `stderr` rather than an empty string.
2. Do not hardcode `localhost`. Ask the test server for its host instead.
3. Convert the process output to unicode. I assume this was a remnant from Python 2. (Not actually a bugfix.)
My assumption is that this doesn't change anything on Travis but should fix the GH Actions once they're rebased.

Fix IPMI tests in an IPv6 world

---

conpot/protocols/IEC104/DeviceDataController.py
conpot/protocols/IEC104/IEC104.py
conpot/protocols/IEC104/frames.py
conpot/templates/IEC104/template.xml
conpot/tests/test_iec104_server.py

Set the IEC104 common address (aka station address) in the template rather than hardcoding it.
Cf. the comment at the top of`frames.py`: 
https://github.com/mushorg/conpot/blob/237b1563eeffc42c8741d5a078a2fa22b1dff772/conpot/protocols/IEC104/frames.py#L21-L22

IEC104: Move station address to databus

---

conpot/core/loggers/helpers.py

Possible fix for the issue #554
JSONs generated with this fix have non empty **request** and response **fields**.
Byte values are represented like this: {"request": **b'deadbeef'**} in JSON

Fix for bytes type in JSON logging

---

conpot/emulators/misc/sysinfo.py
conpot/protocols/snmp/databus_mediator.py
conpot/templates/snmp/snmp/snmp.xml
conpot/templates/snmp/template.xml
requirements.txt

This PR adds a new SNMP template and several emulators capable of reporting things like CPU-Load, PacketsSent, BytesRecv and TotalRam.

Add some Emulators and expand on SNMP capabilities

---

Dockerfile

Errors that are addressed:
1. Permission Errors - Creating directories with appropriate ownership
2. Adding missing Directories 
With those fixes conpot can run by running docker-compose up 🙃

feat: fixing docker build

---

conpot/core/__init__.py
conpot/core/session_manager.py

This is a simple delete session functionality. It is useful so that when a sessions quits or closes, it doesn't also time out after some time.

Delete session functionality
